#!/usr/bin/env sh

# mouse settings
yabai -m config focus_follows_mouse                                         autoraise
yabai -m config mouse_follows_focus                                         on

# general space settings
yabai -m config layout                                                      bsp
yabai -m config top_padding                                                 5
yabai -m config bottom_padding                                              5
yabai -m config left_padding                                                5
yabai -m config right_padding                                               5
yabai -m config window_gap                                                  5

# window management settings
yabai -m rule --add app="Tomito"                                            manage=off  layer=above
yabai -m rule --add app="Kit"                                               manage=off  layer=above

# bind applications to spaces
yabai -m rule --add app="Arc"                                               display=1   space=1
yabai -m rule --add app="WebStorm"                                          display=2   space=1
yabai -m rule --add app="Discord"                                           display=3   space=2
yabai -m rule --add app="TIDAL"                                             display=3   space=1

echo "yabai configuration loaded.."
